//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;

using LinqToDB;
using LinqToDB.Mapping;

namespace Attribution.Dal
{
	/// <summary>
	/// Database       : Attribution
	/// Data Source    : tcp://ghost.local.com:5432
	/// Server Version : 10.6
	/// </summary>
	public partial class AttributionDb : LinqToDB.Data.DataConnection
	{
		public ITable<ActionTypeDb>        ActionTypes       { get { return this.GetTable<ActionTypeDb>(); } }
		public ITable<ChannelAttributesDb> ChannelAttributes { get { return this.GetTable<ChannelAttributesDb>(); } }
		public ITable<ChannelDb>           Channels          { get { return this.GetTable<ChannelDb>(); } }
		public ITable<UrlReferrerDb>       UrlReferrers      { get { return this.GetTable<UrlReferrerDb>(); } }
		public ITable<UserActionDb>        UserActions       { get { return this.GetTable<UserActionDb>(); } }

		partial void InitMappingSchema()
		{
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="public", Name="action_types")]
	public partial class ActionTypeDb
	{
		[Column("id"),          PrimaryKey,  NotNull] public int    Id          { get; set; } // integer
		[Column("name"),                     NotNull] public string Name        { get; set; } // character varying(100)
		[Column("description"),    Nullable         ] public string Description { get; set; } // character varying(500)
	}

	[Table(Schema="public", Name="channel_attributes")]
	public partial class ChannelAttributesDb
	{
		[Column("id"),              PrimaryKey,  Identity] public long   Id            { get; set; } // bigint
		[Column("hash"),            NotNull              ] public long   Hash          { get; set; } // bigint
		[Column("utm_source"),         Nullable          ] public string UtmSource     { get; set; } // character varying(500)
		[Column("utm_medium"),         Nullable          ] public string UtmMedium     { get; set; } // character varying(500)
		[Column("utm_campaign"),       Nullable          ] public string UtmCampaign   { get; set; } // character varying(500)
		[Column("utm_term"),           Nullable          ] public string UtmTerm       { get; set; } // character varying(500)
		[Column("utm_content"),        Nullable          ] public string UtmContent    { get; set; } // character varying(500)
		[Column("utm_agency"),         Nullable          ] public string UtmAgency     { get; set; } // character varying(500)
		[Column("utm_partner_id"),     Nullable          ] public string UtmPartnerId  { get; set; } // character varying(500)
		[Column("utm_campaign_id"),    Nullable          ] public string UtmCampaignId { get; set; } // character varying(500)
		[Column("utm_ad_type"),        Nullable          ] public string UtmAdType     { get; set; } // character varying(500)
		[Column("channel_id"),         Nullable          ] public int?   ChannelId     { get; set; } // integer
		[Column("url_referrer_id"),    Nullable          ] public int?   UrlReferrerId { get; set; } // integer
		[Column("unparsed_data"),      Nullable          ] public string UnparsedData  { get; set; } // text
	}

	[Table(Schema="public", Name="channels")]
	public partial class ChannelDb
	{
		[Column("id"),               PrimaryKey,  Identity] public int    Id              { get; set; } // integer
		[Column("owner"),            NotNull              ] public string Owner           { get; set; } // character varying(100)
		[Column("contract"),            Nullable          ] public string Contract        { get; set; } // character varying(80)
		[Column("price_terms"),         Nullable          ] public string PriceTerms      { get; set; } // character varying(1000)
		[Column("partner_name"),        Nullable          ] public string PartnerName     { get; set; } // character varying(100)
		[Column("contacts_email"),      Nullable          ] public string ContactsEmail   { get; set; } // character varying(100)
		[Column("contacts_phone"),      Nullable          ] public string ContactsPhone   { get; set; } // character varying(20)
		[Column("contacts_website"),    Nullable          ] public string ContactsWebsite { get; set; } // character varying(100)
		[Column("description"),         Nullable          ] public string Description     { get; set; } // character varying(1000)
		[Column("comments"),            Nullable          ] public string Comments        { get; set; } // character varying(1000)
		[Column("name"),                Nullable          ] public string Name            { get; set; } // character varying(100)
	}

	[Table(Schema="public", Name="url_referrers")]
	public partial class UrlReferrerDb
	{
		[Column("id"),         PrimaryKey,  Identity] public int    Id        { get; set; } // integer
		[Column("host"),       NotNull              ] public string Host      { get; set; } // character varying(200)
		[Column("channel_id"),    Nullable          ] public int?   ChannelId { get; set; } // integer
		[Column("is_deleted"), NotNull              ] public bool   IsDeleted { get; set; } // boolean
	}

	[Table(Schema="public", Name="user_actions")]
	public partial class UserActionDb
	{
		[Column("id"),                    PrimaryKey,  Identity] public long     Id                  { get; set; } // bigint
		[Column("user_id"),               NotNull              ] public long     UserId              { get; set; } // bigint
		[Column("action_datetime_utc"),   NotNull              ] public DateTime ActionDatetimeUtc   { get; set; } // timestamp (6) without time zone
		[Column("action_type_id"),        NotNull              ] public int      ActionTypeId        { get; set; } // integer
		[Column("object_type"),           NotNull              ] public int      ObjectType          { get; set; } // integer
		[Column("object_id"),             NotNull              ] public long     ObjectId            { get; set; } // bigint
		[Column("partner_id"),               Nullable          ] public string   PartnerId           { get; set; } // character varying(50)
		[Column("campaign_id"),              Nullable          ] public string   CampaignId          { get; set; } // character varying(50)
		[Column("channel_attributes_id"),    Nullable          ] public long?    ChannelAttributesId { get; set; } // bigint
		[Column("initiator_id"),             Nullable          ] public int?     InitiatorId         { get; set; } // integer
		[Column("initiator_type"),           Nullable          ] public int?     InitiatorType       { get; set; } // integer
		[Column("object_guid"),              Nullable          ] public Guid?    ObjectGuid          { get; set; } // uuid
		[Column("lingering_hash"),           Nullable          ] public long?    LingeringHash       { get; set; } // bigint
		[Column("actual_hash"),              Nullable          ] public long?    ActualHash          { get; set; } // bigint
	}
}

#pragma warning restore 1591
