FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /src

# Copy source files and build project
COPY . ./
RUN dotnet publish ./src/Attribution.UserActionService/Attribution.UserActionService.csproj -c Release -o /app

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/runtime:2.2
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "Attribution.UserActionService.dll"]